name: Run all D Tests
on: [push, pull_request]

jobs:
  test:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        #dc: [dmd-latest, ldc-latest, dmd-2.102.0, ldc-1.30.0]
        dc: [dmd-2.102.0, ldc-1.30.0]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        run: dub test
